export default class Items {
  ItemGuid: string
  Reg: string
  Old_Reg: string
  Reg_changeDate: string
  CaptureDate: string
  DataCapturerName: string
  ItemMakModGuid: string
  ItemTypeGuid: string
  ItemCatg: string
  ColourGuid: string
  Votecode: string
  ChassisNo: string
  EngineNo: string
  MeterType: string
  MeterRead: number
  MeterReadDate: string
  MeterOffset: string
  TerminalYear: string
  BatteryGuid: string
  FrontTyreGuid: string
  RearTyreGuid: string
  LicenceDate: string
  COFDate: string
  DriverName: string
  MechAvail: string
  MonthlyAveKM: string
  PlantUsage: string
  Refurb: string
  Archive: string
  ArchiveDate: string
  RentalVehicle: string
  SubsidisedVehicle: string
  Autocard: string
  HourRate: string
  DailyRate: string
  KmRate: string
  StandbyRate: string
  ItemBud: string
  LogType: string
  CaptureName: string
  StaffGuid: string
  Inspectiondate: string
  ManufYear: string
  LocDate: string
  LocItemCode: string
  LicDiskRec: string
  LicCost: number
  LicAddCost: string
  LicCostCentGuid: string
  };
