import moment from 'moment';
export default class StaffDetails {
  StaffGuid: string;
  StaffCode: string;
  StaffCatgGuid: string;
  StaffRate: number;
  StaffSurname: string;
  StaffFirstName: string;
  StaffEmployeeNo: string;
  PDP_No: string;
  PDP_ExpDate: string;
  Lic_Nov: string;
  Lic_Code: string;
  Lic_CommDate: string;
  Lic_ExpDate: string;
  Active: string;
  CaptureName: string;
  CaptureDate = moment().format('YYYY-MM-DD HH:mm');
  EmployDate: string;
  IDno: string;
  Lic_No0: string;
  Lic_No1: string;
  Lic_No2: string;
  Lic_No3: string;
  Lic_No4: string;
  Lic_No5: string;
  Lic_Code0: string;
  Lic_Code1: string;
  Lic_Code2: string;
  Lic_Code3: string;
  Lic_Code4: string;
  Lic_Code5: string;
  Lic_CommDate0: string;
  Lic_CommDate1: string;
  Lic_CommDate2: string;
  Lic_CommDate3: string;
  Lic_CommDate4: string;
  Lic_CommDate5: string;
  Lic_ExpDate0: string;
  Lic_ExpDate1: string;
  Lic_ExpDate2: string;
  Lic_ExpDate3: string;
  Lic_ExpDate4: string;
  Lic_ExpDate5: string;
}
