export class AccidentManagement {
  LossContGuid: string
  LossControlNo: string
  DateOpen: string
  DateClosed: string
  Agentguid: string
  agentName: string
  Itemguid: string
  registration: string[]
  LossTypeguid: string
  lossType: string
  LossDate: string
  LossDetails: string
  Reported: string
  DateReported: string
  Reportbyguid: string
  reportedBy: string
  DriverGuid: string[]
  DriverID: string
  driverName: string
  TripAut: string[]
  Policerepdate: string
  PoliceStation: string
  Casenumber: string
  AccidentRep: string[]
  AccRepDate: string
  OtherVeh_Party: string
  Forfeiture: string[]
  Det_Liability: string[]
  Costingdocs: string[]
  LossContActguid: string[]
  lossContAction: string
  amount: number
  AmountRec: number[]
  FileNumber: string
  Capturedate: string
  Capturename: string
}
