import moment from 'moment';
export class Asset {
  ItemGuid: string;
  Reg: string;
  Old_Reg: string;
  Reg_changeDate: string;
  CaptureDate = moment().format('YYYY-MM-DD HH:mm');
  DataCapturerName: string;
  ItemMakModGuid: string;
  ItemTypeGuid: string;
  ItemCatg: string;
  ColourGuid: string;
  ChassisNo: string;
  EngineNo: string;
  BatteryGuid: string;
  FrontTyreGuid: string;
  RearTyreGuid: string;
  COFDate: string;
  DriverName: string;
  PlantUsage: string;
  Archive: string;
  ArchiveDate: string;
  RentalVehicle: string;
  SubsidisedVehicle: string;
  LogType: string;
  CaptureName: string;
  StaffGuid: string;
  Inspectiondate: string;
  LocDate: string;
  LocItemCode: string;
  LicDiskRec: string;
  LicCost: number;
  LicAddCost: number;
  LicCostCentGuid: string;
  MeterType: string;
  MeterRead: number;
  MeterReadDate: string;
  MeterOffset: number;
  LicenceDate: string;
  HourRate: number;
  KmRate: number;
  DailyRate: number;
  StandbyRate: number;
  ManufYear: string;
  TerminalYear: string;
  Votecode: string;
  ItemBud: number;
  MechAvail: number;
  MonthlyAveKM: number;
  Refurb = false;
  Autocard = false;
  rentalVehicle = false;
  govSubsidisedVeh = false;
  purchDate: string;
}
