export class JobCard {
  JobCardGuid: string;
  JobCardNo: string;
  ReportedDate: string;
  StartedDate: string;
  CompletedDate: string;
  StaffGuid: string;
  ItemGuid: string;
  CaptureName: string;
  CaptureDate: string = new Date().toString();
  ServTypeGuid: string;
  Item: string;
  RegIndex: string;
  EstCost: number;
  EstCompDate: string;
  driverOrOpGuid: string;
  registrationNo: string;
  makeAndModel: string;
  assetType: string;
  engineNo: string;
  chassieNo: string;
  meterReading: number;
  meterReadingUnt: string;
  meterReadingDate: string;
  manufacturerDate: string;
  warrantyPeriod: string;
  warrantyExpiryDate: string;
  alternateId1: string;
  location: string;
  Defects: string;
  serviceType: string;
  partsForServType: string[] = ['', '', '', '', ''];
  componentName: string;
  engine: string;
  transmission: string;
  warranty: number;
  expiryDate: string;
  oilGrade: string;
  oilCapLtrs: string;
  totalHours: number;
  mechanicSignature: string;
  foremanSignature: string;
  operatorSignature: string;
}
