import moment from 'moment';
export default class LossControl {
  LossContGuid: string;
  LossControlNo: number;
  DateOpen: string;
  DateClosed: string;
  Agentguid: string;
  Itemguid: string;
  LossTypeguid: string;
  LossDate: string;
  LossDetails: string;
  Reported: boolean;
  DateReported: string;
  Reportbyguid: string;
  DriverGuid: string;
  DriverID: string;
  Policerepdate: string;
  PoliceStation: string;
  Casenumber: string;
  AccidentRep: boolean;
  AccRepDate: string;
  OtherVeh_Party: string;
  Forfeiture: boolean;
  Det_Liability: boolean;
  Costingdocs: boolean;
  LossContActguid: string;
  amount: number;
  FileNumber: string;
  Capturedate = moment().format('YYYY-MM-DD HH:mm');
  Capturename: string;
  TripAut: boolean;
  AmountRec: number;
}
