export default class Revenue {
  RevenueGuid: string;
  RevenueDate: string;
  CaptureDate: string = new Date().toString();
  Timeout: string;
  ClientGuid: string;
  RevenueRef: string;
  ItemGuid: string;
  NoHours = 0;
  HourRate = 0;
  NoKm = 0;
  KmRate = 0;
  NoDays = 0;
  DailyRate = 0;
  StandbyHours = 0;
  StandbyRate = 0;
  Discount = 0;
  CaptureName: string;
  RegIndex: string;
  NoOvertime = 0;
  OvertimeRate = 0;
  NoWeekend = 0;
  WeekendRate = 0;
  OtherRevenue = 0;
  Deductions = 0;
  Vat = 0;
  IncVat: string;
  OtherRevenueComm: string;
  DeductionsComm: string;
  Total = 0;
  CostCentguid: string;
  NoRain = 0;
  RainRate = 0;
}
